### ISSUE TITLE
MergeIdenticalTickets - Add as a note

### ISSUE THREAD

**Issue by ghost** [reneeb/otrs-MergeIdenticalTickets#1]
Hello

Now we have a filter that merge identical tickets. The problem is that everytime when he merge a ticket he create a new one. It is possible to add a identical ticket as a note?
So that we have 1 ticket with for example 5 notes?
They check the sender and subject. If they are similar they will merge.

**Comment by reneeb** [comment]
done with commit dff62295a22e3ef7cb9466a5dd7d7f7d24ee8858
